// Catalogue complet des APIs disponibles dans Ronako.
// hasToolDef = cÃ¢blÃ© dans la boucle tool use (Phase 8).
// keyField = nom de la clÃ© dans le keyring OS.

export interface ApiEntry {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: ApiCategory;
  pricing: string;
  keyField: string;
  docsUrl?: string;
  hasToolDef: boolean;
}

export type ApiCategory =
  | "generation"
  | "search"
  | "productivity"
  | "dev"
  | "communication"
  | "business"
  | "analytics";

export const CATEGORY_META: Record<ApiCategory, { label: string; icon: string; color: string }> = {
  generation:   { label: "GÃ©nÃ©ration IA",   icon: "ðŸŽ¨", color: "text-pink-400" },
  search:       { label: "Recherche & Data", icon: "ðŸ”", color: "text-blue-400" },
  productivity: { label: "ProductivitÃ©",     icon: "ðŸ’¼", color: "text-purple-400" },
  dev:          { label: "Dev & Code",       icon: "ðŸ’»", color: "text-emerald-400" },
  communication:{ label: "Communication",    icon: "ðŸ“§", color: "text-yellow-400" },
  business:     { label: "Business & CRM",   icon: "ðŸ’³", color: "text-orange-400" },
  analytics:    { label: "Analytics",        icon: "ðŸ“Š", color: "text-cyan-400" },
};

export const API_CATALOG: ApiEntry[] = [
  // â”€â”€ GÃ©nÃ©ration IA â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "openai",
    name: "DALL-E 3",
    description: "GÃ©nÃ©ration d'images haute qualitÃ© par OpenAI. IdÃ©al pour illustrations, logos, visuels marketing.",
    icon: "ðŸŽ¨",
    category: "generation",
    pricing: "$0.04/image",
    keyField: "openai",
    docsUrl: "https://platform.openai.com/docs/guides/images",
    hasToolDef: true,
  },
  {
    id: "bfl",
    name: "Flux Pro (BFL)",
    description: "GÃ©nÃ©ration d'images rÃ©alistes par Black Forest Labs. Plus rapide et moins cher que DALL-E.",
    icon: "âš¡",
    category: "generation",
    pricing: "$0.003/image",
    keyField: "bfl",
    docsUrl: "https://api.bfl.ml",
    hasToolDef: true,
  },
  {
    id: "replicate",
    name: "Replicate",
    description: "AccÃ¨s Ã  des centaines de modÃ¨les IA (Stable Diffusion, Llama, Whisper, etc.).",
    icon: "ðŸ”„",
    category: "generation",
    pricing: "variable",
    keyField: "replicate",
    docsUrl: "https://replicate.com/docs",
    hasToolDef: true,
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "SynthÃ¨se vocale rÃ©aliste. GÃ©nÃ¨re des voix pour podcasts, vidÃ©os, prÃ©sentations.",
    icon: "ðŸŽ™ï¸",
    category: "generation",
    pricing: "$0.18/1k chars",
    keyField: "elevenlabs",
    docsUrl: "https://elevenlabs.io/docs",
    hasToolDef: true,
  },
  {
    id: "runway",
    name: "Runway",
    description: "GÃ©nÃ©ration et Ã©dition vidÃ©o par IA. IdÃ©al pour shorts, publicitÃ©s, teasers.",
    icon: "ðŸŽ¬",
    category: "generation",
    pricing: "$0.05/sec",
    keyField: "runway",
    docsUrl: "https://docs.runwayml.com",
    hasToolDef: true,
  },
  {
    id: "stability",
    name: "Stability AI",
    description: "Stable Diffusion et modÃ¨les de gÃ©nÃ©ration d'images variÃ©s.",
    icon: "ðŸŒŠ",
    category: "generation",
    pricing: "$0.002/image",
    keyField: "stability",
    docsUrl: "https://platform.stability.ai",
    hasToolDef: true,
  },

  // â”€â”€ Recherche & Data â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "tavily",
    name: "Tavily Search",
    description: "Recherche web optimisÃ©e pour les LLMs. RÃ©sultats structurÃ©s avec rÃ©sumÃ©s.",
    icon: "ðŸ”",
    category: "search",
    pricing: "$0.001/req",
    keyField: "tavily",
    docsUrl: "https://docs.tavily.com",
    hasToolDef: true,
  },
  {
    id: "brave",
    name: "Brave Search",
    description: "Recherche web sans tracking. API gratuite (up to 2000 req/mois).",
    icon: "ðŸ¦",
    category: "search",
    pricing: "Gratuit / $3/1k",
    keyField: "brave",
    docsUrl: "https://api.search.brave.com/app/documentation",
    hasToolDef: true,
  },
  {
    id: "serper",
    name: "Serper.dev",
    description: "API Google Search. RÃ©sultats Google en temps rÃ©el pour n'importe quelle requÃªte.",
    icon: "ðŸ”Ž",
    category: "search",
    pricing: "$0.001/req",
    keyField: "serper",
    docsUrl: "https://serper.dev",
    hasToolDef: true,
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    description: "Scraping web avancÃ© â€” convertit n'importe quelle page en Markdown propre pour LLMs.",
    icon: "ðŸ”¥",
    category: "search",
    pricing: "$0.001/page",
    keyField: "firecrawl",
    docsUrl: "https://www.firecrawl.dev/docs",
    hasToolDef: true,
  },
  {
    id: "screenshot",
    name: "ScreenshotOne",
    description: "Capture de sites web pour analyse visuelle par les agents.",
    icon: "ðŸ“¸",
    category: "search",
    pricing: "$0.002/capture",
    keyField: "screenshot",
    docsUrl: "https://screenshotone.com",
    hasToolDef: true,
  },
  {
    id: "apify",
    name: "Apify",
    description: "Automatisation web et scraping Ã  grande Ã©chelle. Marketplace d'actors.",
    icon: "ðŸ•·ï¸",
    category: "search",
    pricing: "$5/mois+",
    keyField: "apify",
    docsUrl: "https://docs.apify.com",
    hasToolDef: true,
  },

  // â”€â”€ ProductivitÃ© â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "notion",
    name: "Notion",
    description: "Exporte les livrables directement dans Notion. CrÃ©e pages, databases, docs.",
    icon: "ðŸ““",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "notion",
    docsUrl: "https://developers.notion.com",
    hasToolDef: true,
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Base de donnÃ©es flexible. Les agents peuvent crÃ©er des enregistrements et lire des donnÃ©es.",
    icon: "ðŸ—‚ï¸",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "airtable",
    docsUrl: "https://airtable.com/developers/web/api",
    hasToolDef: true,
  },
  {
    id: "googlesheets",
    name: "Google Sheets",
    description: "Lecture et Ã©criture de tableurs Google. IdÃ©al pour exports de donnÃ©es structurÃ©es.",
    icon: "ðŸ“Š",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "googlesheets",
    docsUrl: "https://developers.google.com/sheets",
    hasToolDef: true,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Envoie des messages, crÃ©e des posts dans des canaux Slack directement.",
    icon: "ðŸ’¬",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "slack",
    docsUrl: "https://api.slack.com",
    hasToolDef: true,
  },
  {
    id: "linear",
    name: "Linear",
    description: "CrÃ©e des issues, mets Ã  jour le roadmap depuis les livrables Ronako.",
    icon: "ðŸ“",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "linear",
    docsUrl: "https://linear.app/docs/api",
    hasToolDef: true,
  },
  {
    id: "jira",
    name: "Jira",
    description: "CrÃ©e et met Ã  jour des tickets Jira depuis les plans d'action gÃ©nÃ©rÃ©s.",
    icon: "ðŸŽ¯",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "jira",
    docsUrl: "https://developer.atlassian.com/cloud/jira",
    hasToolDef: true,
  },

  // â”€â”€ Dev & Code â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "github",
    name: "GitHub",
    description: "CrÃ©e des commits, ouvre des PRs, lit des repos depuis les agents.",
    icon: "ðŸ™",
    category: "dev",
    pricing: "Gratuit*",
    keyField: "github",
    docsUrl: "https://docs.github.com/rest",
    hasToolDef: true,
  },
  {
    id: "e2b",
    name: "E2B Sandbox",
    description: "ExÃ©cution de code Python/Node sÃ©curisÃ©e. GÃ©nÃ¨re de vrais fichiers (.xlsx, .pdf, .pptx).",
    icon: "ðŸ–¥ï¸",
    category: "dev",
    pricing: "$0.10/heure",
    keyField: "e2b",
    docsUrl: "https://e2b.dev/docs",
    hasToolDef: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "Alternative GitHub. Push, MRs, pipelines CI/CD depuis les agents.",
    icon: "ðŸ¦Š",
    category: "dev",
    pricing: "Gratuit*",
    keyField: "gitlab",
    docsUrl: "https://docs.gitlab.com/ee/api",
    hasToolDef: true,
  },
  {
    id: "vercel",
    name: "Vercel",
    description: "DÃ©clenche des dÃ©ploiements, gÃ¨re les domaines et variables d'environnement.",
    icon: "â–²",
    category: "dev",
    pricing: "Gratuit*",
    keyField: "vercel",
    docsUrl: "https://vercel.com/docs/rest-api",
    hasToolDef: true,
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "BDD PostgreSQL + auth + storage. Lit et Ã©crit des donnÃ©es depuis les agents.",
    icon: "âš¡",
    category: "dev",
    pricing: "Gratuit*",
    keyField: "supabase",
    docsUrl: "https://supabase.com/docs/reference/api",
    hasToolDef: true,
  },

  // â”€â”€ Communication â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "Envoie des emails transactionnels. Les sÃ©quences gÃ©nÃ©rÃ©es par Leo partent directement.",
    icon: "ðŸ“§",
    category: "communication",
    pricing: "$0.001/email",
    keyField: "sendgrid",
    docsUrl: "https://docs.sendgrid.com",
    hasToolDef: true,
  },
  {
    id: "resend",
    name: "Resend",
    description: "API email moderne pour devs. Gratuit jusqu'Ã  3000 emails/mois.",
    icon: "âœ‰ï¸",
    category: "communication",
    pricing: "Gratuit / $20/mois",
    keyField: "resend",
    docsUrl: "https://resend.com/docs",
    hasToolDef: true,
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "CrÃ©e et envoie des campagnes email. GÃ¨re les listes de contacts.",
    icon: "ðŸ’",
    category: "communication",
    pricing: "Gratuit*",
    keyField: "mailchimp",
    docsUrl: "https://mailchimp.com/developer/marketing/api",
    hasToolDef: true,
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "SMS, WhatsApp, appels vocaux. Envoie des notifications depuis les agents.",
    icon: "ðŸ“±",
    category: "communication",
    pricing: "$0.008/SMS",
    keyField: "twilio",
    docsUrl: "https://www.twilio.com/docs",
    hasToolDef: true,
  },

  // â”€â”€ Business & CRM â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "stripe",
    name: "Stripe",
    description: "Lit les donnÃ©es de paiement, crÃ©e des liens de paiement, analyse les revenus.",
    icon: "ðŸ’³",
    category: "business",
    pricing: "Gratuit*",
    keyField: "stripe",
    docsUrl: "https://stripe.com/docs/api",
    hasToolDef: true,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "CRM â€” crÃ©e des contacts, deals, notes Ã  partir des livrables gÃ©nÃ©rÃ©s.",
    icon: "ðŸ”¶",
    category: "business",
    pricing: "Gratuit*",
    keyField: "hubspot",
    docsUrl: "https://developers.hubspot.com",
    hasToolDef: true,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "CRM enterprise â€” sync les donnÃ©es depuis les analyses des agents.",
    icon: "â˜ï¸",
    category: "business",
    pricing: "Payant",
    keyField: "salesforce",
    docsUrl: "https://developer.salesforce.com/docs",
    hasToolDef: true,
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "CRM ventes â€” crÃ©e des deals et activitÃ©s depuis les stratÃ©gies commerciales gÃ©nÃ©rÃ©es.",
    icon: "ðŸ“ˆ",
    category: "business",
    pricing: "Gratuit*",
    keyField: "pipedrive",
    docsUrl: "https://developers.pipedrive.com",
    hasToolDef: true,
  },

  // â”€â”€ Analytics â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "ga4",
    name: "Google Analytics 4",
    description: "Lit les donnÃ©es de trafic. Sofia peut analyser les vraies perfs SEO.",
    icon: "ðŸ“Š",
    category: "analytics",
    pricing: "Gratuit",
    keyField: "ga4",
    docsUrl: "https://developers.google.com/analytics",
    hasToolDef: true,
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Analytics produit â€” analyse les events utilisateurs pour les rapports SaaS.",
    icon: "ðŸ“‰",
    category: "analytics",
    pricing: "Gratuit*",
    keyField: "mixpanel",
    docsUrl: "https://developer.mixpanel.com",
    hasToolDef: true,
  },
  {
    id: "plausible",
    name: "Plausible",
    description: "Analytics privacy-first. Lit les stats de trafic sans cookies.",
    icon: "ðŸŒ¿",
    category: "analytics",
    pricing: "$9/mois",
    keyField: "plausible",
    docsUrl: "https://plausible.io/docs/stats-api",
    hasToolDef: true,
  },
];

export function getApisByCategory(category: ApiCategory): ApiEntry[] {
  return API_CATALOG.filter((a) => a.category === category);
}

export function getApiById(id: string): ApiEntry | undefined {
  return API_CATALOG.find((a) => a.id === id);
}
