// Catalogue complet des APIs disponibles dans Ronako.
// hasToolDef = câblé dans la boucle tool use (Phase 8).
// keyField = nom de la clé dans le keyring OS.

export interface ApiEntry {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: ApiCategory;
  pricing: string;
  keyField: string;
  docsUrl?: string;
  hasToolDef: boolean;
  comingSoon?: boolean;
}

export type ApiCategory =
  | "generation"
  | "search"
  | "productivity"
  | "dev"
  | "communication"
  | "business"
  | "analytics";

export const CATEGORY_META: Record<ApiCategory, { label: string; icon: string; color: string }> = {
  generation:   { label: "Génération IA",   icon: "🎨", color: "text-pink-400" },
  search:       { label: "Recherche & Data", icon: "🔍", color: "text-blue-400" },
  productivity: { label: "Productivité",     icon: "💼", color: "text-purple-400" },
  dev:          { label: "Dev & Code",       icon: "💻", color: "text-emerald-400" },
  communication:{ label: "Communication",    icon: "📧", color: "text-yellow-400" },
  business:     { label: "Business & CRM",   icon: "💳", color: "text-orange-400" },
  analytics:    { label: "Analytics",        icon: "📊", color: "text-cyan-400" },
};

export const API_CATALOG: ApiEntry[] = [
  // ── Génération IA ─────────────────────────────────────────────────────────
  {
    id: "openai",
    name: "DALL-E 3",
    description: "Génération d'images haute qualité par OpenAI. Idéal pour illustrations, logos, visuels marketing.",
    icon: "🎨",
    category: "generation",
    pricing: "$0.04/image",
    keyField: "openai",
    docsUrl: "https://platform.openai.com/docs/guides/images",
    hasToolDef: true,
  },
  {
    id: "bfl",
    name: "Flux Pro (BFL)",
    description: "Génération d'images réalistes par Black Forest Labs. Plus rapide et moins cher que DALL-E.",
    icon: "⚡",
    category: "generation",
    pricing: "$0.003/image",
    keyField: "bfl",
    docsUrl: "https://api.bfl.ml",
    hasToolDef: true,
  },
  {
    id: "replicate",
    name: "Replicate",
    description: "Accès à des centaines de modèles IA (Stable Diffusion, Llama, Whisper, etc.).",
    icon: "🔄",
    category: "generation",
    pricing: "variable",
    keyField: "replicate",
    docsUrl: "https://replicate.com/docs",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "Synthèse vocale réaliste. Génère des voix pour podcasts, vidéos, présentations.",
    icon: "🎙️",
    category: "generation",
    pricing: "$0.18/1k chars",
    keyField: "elevenlabs",
    docsUrl: "https://elevenlabs.io/docs",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "runway",
    name: "Runway",
    description: "Génération et édition vidéo par IA. Idéal pour shorts, publicités, teasers.",
    icon: "🎬",
    category: "generation",
    pricing: "$0.05/sec",
    keyField: "runway",
    docsUrl: "https://docs.runwayml.com",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "stability",
    name: "Stability AI",
    description: "Stable Diffusion et modèles de génération d'images variés.",
    icon: "🌊",
    category: "generation",
    pricing: "$0.002/image",
    keyField: "stability",
    docsUrl: "https://platform.stability.ai",
    hasToolDef: false,
    comingSoon: true,
  },

  // ── Recherche & Data ──────────────────────────────────────────────────────
  {
    id: "tavily",
    name: "Tavily Search",
    description: "Recherche web optimisée pour les LLMs. Résultats structurés avec résumés.",
    icon: "🔍",
    category: "search",
    pricing: "$0.001/req",
    keyField: "tavily",
    docsUrl: "https://docs.tavily.com",
    hasToolDef: true,
  },
  {
    id: "brave",
    name: "Brave Search",
    description: "Recherche web sans tracking. API gratuite (up to 2000 req/mois).",
    icon: "🦁",
    category: "search",
    pricing: "Gratuit / $3/1k",
    keyField: "brave",
    docsUrl: "https://api.search.brave.com/app/documentation",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "serper",
    name: "Serper.dev",
    description: "API Google Search. Résultats Google en temps réel pour n'importe quelle requête.",
    icon: "🔎",
    category: "search",
    pricing: "$0.001/req",
    keyField: "serper",
    docsUrl: "https://serper.dev",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    description: "Scraping web avancé — convertit n'importe quelle page en Markdown propre pour LLMs.",
    icon: "🔥",
    category: "search",
    pricing: "$0.001/page",
    keyField: "firecrawl",
    docsUrl: "https://www.firecrawl.dev/docs",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "screenshot",
    name: "ScreenshotOne",
    description: "Capture de sites web pour analyse visuelle par les agents.",
    icon: "📸",
    category: "search",
    pricing: "$0.002/capture",
    keyField: "screenshot",
    docsUrl: "https://screenshotone.com",
    hasToolDef: false,
  },
  {
    id: "apify",
    name: "Apify",
    description: "Automatisation web et scraping à grande échelle. Marketplace d'actors.",
    icon: "🕷️",
    category: "search",
    pricing: "$5/mois+",
    keyField: "apify",
    docsUrl: "https://docs.apify.com",
    hasToolDef: false,
    comingSoon: true,
  },

  // ── Productivité ──────────────────────────────────────────────────────────
  {
    id: "notion",
    name: "Notion",
    description: "Exporte les livrables directement dans Notion. Crée pages, databases, docs.",
    icon: "📓",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "notion",
    docsUrl: "https://developers.notion.com",
    hasToolDef: true,
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Base de données flexible. Les agents peuvent créer des enregistrements et lire des données.",
    icon: "🗂️",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "airtable",
    docsUrl: "https://airtable.com/developers/web/api",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "googlesheets",
    name: "Google Sheets",
    description: "Lecture et écriture de tableurs Google. Idéal pour exports de données structurées.",
    icon: "📊",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "googlesheets",
    docsUrl: "https://developers.google.com/sheets",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Envoie des messages, crée des posts dans des canaux Slack directement.",
    icon: "💬",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "slack",
    docsUrl: "https://api.slack.com",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "linear",
    name: "Linear",
    description: "Crée des issues, mets à jour le roadmap depuis les livrables Ronako.",
    icon: "📐",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "linear",
    docsUrl: "https://linear.app/docs/api",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "jira",
    name: "Jira",
    description: "Crée et met à jour des tickets Jira depuis les plans d'action générés.",
    icon: "🎯",
    category: "productivity",
    pricing: "Gratuit*",
    keyField: "jira",
    docsUrl: "https://developer.atlassian.com/cloud/jira",
    hasToolDef: false,
    comingSoon: true,
  },

  // ── Dev & Code ────────────────────────────────────────────────────────────
  {
    id: "github",
    name: "GitHub",
    description: "Crée des commits, ouvre des PRs, lit des repos depuis les agents.",
    icon: "🐙",
    category: "dev",
    pricing: "Gratuit*",
    keyField: "github",
    docsUrl: "https://docs.github.com/rest",
    hasToolDef: true,
  },
  {
    id: "e2b",
    name: "E2B Sandbox",
    description: "Exécution de code Python/Node sécurisée. Génère de vrais fichiers (.xlsx, .pdf, .pptx).",
    icon: "🖥️",
    category: "dev",
    pricing: "$0.10/heure",
    keyField: "e2b",
    docsUrl: "https://e2b.dev/docs",
    hasToolDef: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "Alternative GitHub. Push, MRs, pipelines CI/CD depuis les agents.",
    icon: "🦊",
    category: "dev",
    pricing: "Gratuit*",
    keyField: "gitlab",
    docsUrl: "https://docs.gitlab.com/ee/api",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "vercel",
    name: "Vercel",
    description: "Déclenche des déploiements, gère les domaines et variables d'environnement.",
    icon: "▲",
    category: "dev",
    pricing: "Gratuit*",
    keyField: "vercel",
    docsUrl: "https://vercel.com/docs/rest-api",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "BDD PostgreSQL + auth + storage. Lit et écrit des données depuis les agents.",
    icon: "⚡",
    category: "dev",
    pricing: "Gratuit*",
    keyField: "supabase",
    docsUrl: "https://supabase.com/docs/reference/api",
    hasToolDef: false,
    comingSoon: true,
  },

  // ── Communication ─────────────────────────────────────────────────────────
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "Envoie des emails transactionnels. Les séquences générées par Leo partent directement.",
    icon: "📧",
    category: "communication",
    pricing: "$0.001/email",
    keyField: "sendgrid",
    docsUrl: "https://docs.sendgrid.com",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "resend",
    name: "Resend",
    description: "API email moderne pour devs. Gratuit jusqu'à 3000 emails/mois.",
    icon: "✉️",
    category: "communication",
    pricing: "Gratuit / $20/mois",
    keyField: "resend",
    docsUrl: "https://resend.com/docs",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Crée et envoie des campagnes email. Gère les listes de contacts.",
    icon: "🐒",
    category: "communication",
    pricing: "Gratuit*",
    keyField: "mailchimp",
    docsUrl: "https://mailchimp.com/developer/marketing/api",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "SMS, WhatsApp, appels vocaux. Envoie des notifications depuis les agents.",
    icon: "📱",
    category: "communication",
    pricing: "$0.008/SMS",
    keyField: "twilio",
    docsUrl: "https://www.twilio.com/docs",
    hasToolDef: false,
    comingSoon: true,
  },

  // ── Business & CRM ────────────────────────────────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    description: "Lit les données de paiement, crée des liens de paiement, analyse les revenus.",
    icon: "💳",
    category: "business",
    pricing: "Gratuit*",
    keyField: "stripe",
    docsUrl: "https://stripe.com/docs/api",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "CRM — crée des contacts, deals, notes à partir des livrables générés.",
    icon: "🔶",
    category: "business",
    pricing: "Gratuit*",
    keyField: "hubspot",
    docsUrl: "https://developers.hubspot.com",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "CRM enterprise — sync les données depuis les analyses des agents.",
    icon: "☁️",
    category: "business",
    pricing: "Payant",
    keyField: "salesforce",
    docsUrl: "https://developer.salesforce.com/docs",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "CRM ventes — crée des deals et activités depuis les stratégies commerciales générées.",
    icon: "📈",
    category: "business",
    pricing: "Gratuit*",
    keyField: "pipedrive",
    docsUrl: "https://developers.pipedrive.com",
    hasToolDef: false,
    comingSoon: true,
  },

  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    id: "ga4",
    name: "Google Analytics 4",
    description: "Lit les données de trafic. Sofia peut analyser les vraies perfs SEO.",
    icon: "📊",
    category: "analytics",
    pricing: "Gratuit",
    keyField: "ga4",
    docsUrl: "https://developers.google.com/analytics",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Analytics produit — analyse les events utilisateurs pour les rapports SaaS.",
    icon: "📉",
    category: "analytics",
    pricing: "Gratuit*",
    keyField: "mixpanel",
    docsUrl: "https://developer.mixpanel.com",
    hasToolDef: false,
    comingSoon: true,
  },
  {
    id: "plausible",
    name: "Plausible",
    description: "Analytics privacy-first. Lit les stats de trafic sans cookies.",
    icon: "🌿",
    category: "analytics",
    pricing: "$9/mois",
    keyField: "plausible",
    docsUrl: "https://plausible.io/docs/stats-api",
    hasToolDef: false,
    comingSoon: true,
  },
];

export function getApisByCategory(category: ApiCategory): ApiEntry[] {
  return API_CATALOG.filter((a) => a.category === category);
}

export function getApiById(id: string): ApiEntry | undefined {
  return API_CATALOG.find((a) => a.id === id);
}
