import type { SkillPack } from "@/types";
import { now } from "@/lib/utils";

// ─── 5 packs de skills prédéfinis ────────────────────────────────────────────
export const SKILL_PACKS: SkillPack[] = [
  {
    id: "ecommerce",
    name: "E-Commerce",
    icon: "🛒",
    description: "SEO produit, copy conversion, conformité légale boutique",
    sector: "ecommerce",
    skills: [
      {
        id: "seo-produit",
        name: "SEO Produit",
        description: "Optimisation pages produit et catégories",
        content: `Pour chaque produit/catégorie : title tag 50-60 chars avec mot-clé principal en tête, meta description 150-160 chars incitative. H1 unique différent du title. URL courte avec mot-clé (sans stop words). Structure les données (prix, stock, avis) en JSON-LD Schema.org. Identifie les requêtes transactionnelles (acheter, prix, livraison, comparatif). Cible les Featured Snippets pour les questions produit fréquentes.`,
        agentIds: ["sofia"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["boutique", "produit", "fiche produit", "e-commerce", "shop"],
        sector: "ecommerce", createdBy: "system",
      },
      {
        id: "copy-conversion",
        name: "Copy Conversion",
        description: "Textes orientés conversion et taux d'achat",
        content: `Méthode AIDA systématique. Fiches produit : bénéfices AVANT caractéristiques, preuve sociale (nombre avis, étoiles, volume vendu), urgence légère (stock limité, délai livraison), CTA visible et spécifique ("Ajouter au panier — Livré en 24h"). Évite le jargon technique sauf si B2B. Objections anticipées dans la description. Prix encadré d'une valeur perçue.`,
        agentIds: ["leo"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["conversion", "vente", "achat", "panier", "boutique"],
        sector: "ecommerce", createdBy: "system",
      },
      {
        id: "legal-ecommerce",
        name: "Légal E-Commerce",
        description: "CGV, mentions légales, conformité RGPD boutique",
        content: `Obligations légales e-commerce FR/EU : CGV obligatoires avec droit de rétractation 14 jours, politique retours claire, mentions légales complètes (SIRET, responsable, hébergeur). RGPD : consentement cookies, politique confidentialité, mentions collecte données. Si paiement en ligne : conformité PCI-DSS, mentions sécurité. Signaler les risques spécifiques au secteur (alimentaire, cosmétique, etc.).`,
        agentIds: ["camille"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["boutique", "cgv", "vente", "retour", "remboursement"],
        sector: "ecommerce", createdBy: "system",
      },
    ],
  },
  {
    id: "saas",
    name: "SaaS",
    icon: "⚡",
    description: "Onboarding, pitch investisseur, architecture scalable",
    sector: "saas",
    skills: [
      {
        id: "onboarding-copy",
        name: "Onboarding Copy",
        description: "Textes d'activation utilisateur et emails séquentiels",
        content: `Onboarding SaaS : focus sur la valeur du premier AHA moment. Emails d'activation J0-J7 : J0 bienvenue + action unique, J1 astuce clé, J3 cas d'usage similaire, J7 relance si inactif. In-app : tooltips contextuels non bloquants, messages de progression, célébration des étapes clés. Ton : ami expert, jamais commercial. Metric d'activation clairement définie.`,
        agentIds: ["leo"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["saas", "activation", "onboarding", "app", "utilisateur"],
        sector: "saas", createdBy: "system",
      },
      {
        id: "pitch-investisseur",
        name: "Pitch Investisseur",
        description: "Structure deck, KPIs, narrative investissement",
        content: `Structure pitch seed/série A : Problème (1 slide, data), Solution (1-2 slides, démo), Marché TAM/SAM/SOM, Business model clair, Traction (MRR, croissance, rétention, NPS), Équipe (exécution > parcours), Compétition (honest, matrice), Ask (montant, use of funds, milestones 18 mois). Narratif : storytelling client avant chiffres. Évite : CAC sans LTV, projections sans hypothèses, buzzwords sans substance.`,
        agentIds: ["omar"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["pitch", "investisseur", "levée", "startup", "deck"],
        sector: "saas", createdBy: "system",
      },
      {
        id: "architecture-scalable",
        name: "Architecture Scalable",
        description: "Patterns techniques pour SaaS multi-tenant",
        content: `SaaS multi-tenant : isolation données (schema-per-tenant vs shared), rate limiting par tenant, feature flags (LaunchDarkly/Flagsmith), observabilité (traces distribuées, métriques par tenant). Auth : OAuth2 + OIDC, RBAC granulaire. Async : queue events, webhooks fiables avec retry. Facturation : Stripe usage-based. DB : connection pooling (PgBouncer), read replicas par région. CDN pour assets. IaC : Terraform ou Pulumi.`,
        agentIds: ["nina"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["saas", "multi-tenant", "scalable", "architecture", "api"],
        sector: "saas", createdBy: "system",
      },
    ],
  },
  {
    id: "local",
    name: "Business Local",
    icon: "📍",
    description: "SEO local, ton de proximité, Google Business",
    sector: "local",
    skills: [
      {
        id: "seo-local",
        name: "SEO Local",
        description: "Visibilité locale, Google Business, citations NAP",
        content: `SEO local : optimiser Google Business Profile (photos, horaires, attributs, posts hebdomadaires). Cohérence NAP (Nom/Adresse/Phone) sur tous les annuaires. Pages de zones géographiques (ville + quartier + code postal). Avis Google : template de demande d'avis + réponses aux avis négatifs. Balises LocalBusiness Schema.org. Cible "near me" + "[service] [ville]". Backlinks locaux : associations, presse locale, partenaires.`,
        agentIds: ["sofia"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["local", "ville", "région", "near me", "proximité", "cabinet", "clinique"],
        sector: "local", createdBy: "system",
      },
      {
        id: "ton-proximite",
        name: "Ton de Proximité",
        description: "Copywriting chaleureux pour business local",
        content: `Ton : chaleureux, humain, ancré localement. Référencer la zone géographique naturellement (pas mécaniquement). Valoriser l'expertise locale et la connaissance du terrain. Équipe mise en avant (prénoms, photos, parcours local). Témoignages clients avec prénom + ville/quartier. Éviter le jargon corporate. Storytelling authentique sur l'histoire locale. CTA personnalisés : "Venez nous rencontrer à [adresse]".`,
        agentIds: ["leo"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["local", "proximité", "artisan", "cabinet", "clinique", "restaurant"],
        sector: "local", createdBy: "system",
      },
    ],
  },
  {
    id: "marketing",
    name: "Marketing Digital",
    icon: "📣",
    description: "Social media, email marketing, stratégie contenu",
    sector: "marketing",
    skills: [
      {
        id: "social-strategy",
        name: "Social Media Strategy",
        description: "Stratégie contenu réseaux sociaux par plateforme",
        content: `Par plateforme : LinkedIn (expertise B2B, format carrousel, jeudi-vendredi matin), Instagram (visuels + Reels 15-30s, hashtags niche 10-15), Twitter/X (opinions tranchées, threads, veille), Facebook (communauté, groupes, events). Règle 80/20 : 80% valeur/éducation, 20% promotion. Fréquence : 3-5x/semaine. Viral hook en première ligne. CTA clair. Analyse hebdomadaire des tops posts.`,
        agentIds: ["leo", "maya"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["social", "réseaux", "instagram", "linkedin", "facebook", "posts"],
        sector: "marketing", createdBy: "system",
      },
      {
        id: "email-marketing",
        name: "Email Marketing",
        description: "Séquences email, deliverability, automation",
        content: `Séquences automatisées : welcome (J0-J7), nurturing (hebdo), réactivation (J30 inactif). Objet : 40 chars max, curiosité ou bénéfice clair, émoticône en tête si B2C. Preheader complémentaire. Structure : une idée = un email. CTA unique et contrasté. Délivrabilité : SPF+DKIM+DMARC, liste propre (suppression bounces 30j), warm-up domaine. A/B test objet systématique. KPIs : open rate >25%, CTR >3%.`,
        agentIds: ["leo"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["email", "newsletter", "mailing", "automation", "séquence"],
        sector: "marketing", createdBy: "system",
      },
    ],
  },
  {
    id: "tech",
    name: "Tech & Dev",
    icon: "🔧",
    description: "Performance web, sécurité renforcée, code quality",
    sector: "tech",
    skills: [
      {
        id: "performance-web",
        name: "Performance Web",
        description: "Core Web Vitals, optimisation front-end",
        content: `Core Web Vitals : LCP <2.5s (images WebP/AVIF, lazy loading, priority hints), INP <200ms (code splitting, defer non-critique), CLS <0.1 (dimensions explicites images, skeleton loaders). Bundle : tree shaking, code splitting par route, compression Brotli. Fonts : font-display swap, preconnect, subset. Cache : CDN edge, stale-while-revalidate. Monitoring : Web Vitals field data (RUM), Lighthouse CI en pipeline.`,
        agentIds: ["nina", "tom"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["performance", "vitals", "lcp", "lighthouse", "optimisation", "front-end"],
        sector: "tech", createdBy: "system",
      },
      {
        id: "securite-renforcee",
        name: "Sécurité Renforcée",
        description: "OWASP Top 10, bonnes pratiques sécurité",
        content: `OWASP Top 10 : injection (parameterized queries), broken auth (MFA, session management), XSS (CSP strict, sanitisation), IDOR (contrôle accès systématique), SSRF (allowlist sortante). Headers sécurité : HSTS, X-Frame-Options, CSP. Secrets : vault (HashiCorp/AWS Secrets Manager), jamais en config/env commité. Audit : dépendances (npm audit, Snyk), SAST en CI. Logs : pas de PII, rotation, alerting anomalies.`,
        agentIds: ["nina", "tom"],
        isActive: true, isTemporary: false, inheritToAll: false,
        triggerKeywords: ["sécurité", "owasp", "xss", "injection", "pentest", "vulnérabilité"],
        sector: "tech", createdBy: "system",
      },
    ],
  },
];

// Générer des IDs stables pour les skills des packs
export function materializeSkillPack(pack: SkillPack): Array<import("@/types").Skill> {
  return pack.skills.map((skill) => ({
    ...skill,
    id: skill.id || `${pack.id}-${skill.name.toLowerCase().replace(/\s+/g, "-")}`,
    createdAt: now(),
    useCount: 0,
    avgScoreImpact: 0,
  }));
}
